[LoadBalancer]
host = "0.0.0.0"
strategy = "LeastConnection"
port = 18080

[[Servers]]
url="https://dogapi.dog/api/v2/breeds"

[[Servers]]
url="https://api.attackontitanapi.com/episodes"

[[Servers]]
url="https://api.attackontitanapi.com/characters"
